// Course Overview page — /showcase/course
// Figma reference: node 96:5854 (Desktop)
// Generated by /layout-generation following ADR-011 landmark grammar.
//
// Pass 1 — Structure:  <main> → AppHeader → 3× <section> → <footer>
// Pass 2 — Components: AppHeader, Breadcrumb, VideoFrame, Accordion/AccordionItem,
//                      Badge, CardVertical, CardHorizontal, ButtonArrow, Button, Heading, Text
// Pass 3 — Spacing:    paddingY via Box inset tokens; gaps via Stack/Inline gap tokens

import { useState } from 'react'
import {
  Accordion,
  AccordionItem,
  AppHeader,
  Badge,
  Box,
  Breadcrumb,
  Button,
  ButtonArrow,
  CardHorizontal,
  CardVertical,
  Divider,
  Heading,
  Inline,
  Stack,
  Text,
  VideoFrame,
} from '@upskill/components'

// ─── Sample data ─────────────────────────────────────────────────────────────
const VIDEO_SRC = 'https://picsum.photos/seed/tenfaces/740/413'
const CARD_IMGS = [
  'https://picsum.photos/seed/changebydesign/452/452',
  'https://picsum.photos/seed/creativeconfidence/452/452',
  'https://picsum.photos/seed/designeveryday/452/452',
  'https://picsum.photos/seed/designthinking/452/452',
]
const BOOK_IMGS = [
  'https://picsum.photos/seed/zenmin/80/80',
  'https://picsum.photos/seed/whereveryougo/80/80',
  'https://picsum.photos/seed/miraclemindful/80/80',
]

const ALL_MODULES = [
  {
    title: 'The Anthropologist',
    subtitle: '4 hours, 30min',
    body: 'Observes human behaviour to find inspiration and identify opportunities for innovation.',
  },
  {
    title: 'The Experimenter',
    subtitle: '4 hours, 30min',
    body: 'The Experimenter is a curious, hands-on innovator who learns by testing and prototyping. They take calculated risks, embrace failure as learning, and drive innovation through rapid iteration and experimentation.',
    defaultOpen: true,
  },
  {
    title: 'The Cross-Pollinator',
    subtitle: '4 hours, 30min',
    body: 'Draws connections across industries, cultures, and disciplines to spark new ideas.',
  },
  {
    title: 'The Hurdler',
    subtitle: '4 hours, 30min',
    body: 'Thrives on constraints, turning obstacles and setbacks into competitive advantages.',
  },
  {
    title: 'The Collaborator',
    subtitle: '4 hours, 30min',
    body: 'Brings diverse teams together, bridging silos to co-create breakthroughs.',
  },
  {
    title: 'The Director',
    subtitle: '4 hours, 30min',
    body: 'Assembles talented casts and sets the stage for creative work to flourish.',
  },
]

const RECOMMENDED_COURSES = [
  { title: 'Change by Design', duration: '12 Hours', certified: true },
  { title: 'Creative Confidence', duration: '12 Hours', certified: true },
  { title: 'The Design of Everyday Things', duration: '12 Hours', certified: true },
  { title: 'The Design Thinking Playbook', duration: '12 Hours', certified: true },
  { title: 'Creative Acts for Curious People', duration: '10 Hours', certified: true },
  { title: 'Sprint', duration: '6 Hours', certified: true },
  { title: 'The Art of Innovation', duration: '8 Hours', certified: true },
  { title: 'Thinking, Fast and Slow', duration: '14 Hours', certified: true },
]

const VISIBLE_MODULES = 3
const PAGE_SIZE = 4

export default function CourseOverview() {
  const [showAll, setShowAll] = useState(false)
  const [page, setPage] = useState(0)

  const visibleModules = showAll ? ALL_MODULES : ALL_MODULES.slice(0, VISIBLE_MODULES)
  const hiddenCount = ALL_MODULES.length - VISIBLE_MODULES
  const totalPages = Math.ceil(RECOMMENDED_COURSES.length / PAGE_SIZE)
  const visibleCourses = RECOMMENDED_COURSES.slice(page * PAGE_SIZE, (page + 1) * PAGE_SIZE)
  const shownCount = Math.min((page + 1) * PAGE_SIZE, RECOMMENDED_COURSES.length)

  return (
    // ── Page ── grammar: exactly one <main> per route (ADR-011)
    <Box as="main">

      {/* ── Header ── grammar: AppHeader satisfies the banner/navigation landmark */}
      {/* Logos are served from apps/showcase/public/ — see index.html for font imports */}
      <AppHeader
        logoSrc="/logo.svg"
        logoSrcDark="/logo-dark.svg"
        logoAlt="UpSkill"
        navItems={[
          { label: 'All Courses', href: '/courses' },
          { label: 'My Courses', href: '/my-courses', active: true },
        ]}
        userAvatarSrc="https://placehold.co/24x24/D15D50/ffffff?text=S"
        userName="Sarah"
        userMenuItems={[
          { value: 'profile', label: 'My Profile' },
          { value: 'settings', label: 'Settings' },
          { value: 'logout', label: 'Log out' },
        ]}
      />

      {/* ── Section 1: Course overview ── aria-label because there is no visible section-level heading */}
      <Box as="section" aria-label="Course overview" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            {/* Breadcrumb renders its own <nav aria-label="Breadcrumb"> */}
            <Breadcrumb
              items={[
                { label: 'Home', href: '/' },
                { label: 'Courses', href: '/courses' },
                { label: 'Course Overview' },
              ]}
            />

            {/* Two-panel — grammar: Inline wrap; each child flex:1 0 0 + minWidth sets stack breakpoint */}
            <Inline wrap align="start" gap="lg">

              {/* ── Left column: video + course description ── */}
              <Stack gap="md" style={{ flex: '1 0 0', minWidth: '34.5rem' }}>

                {/* VideoFrame — usage.when: "displaying a video thumbnail with play overlay" */}
                <VideoFrame src={VIDEO_SRC} alt="The Ten Faces of Innovation — course preview" />

                <Stack gap="sm">
                  <Text size="body-default" color="subtle">
                    <a
                      href="#"
                      style={{ color: 'var(--ds-color-text-link-default)', fontWeight: 600, textDecoration: 'underline' }}
                    >
                      Edward Clark
                    </a>
                    {', Author and educator, MICA'}
                  </Text>

                  <Stack gap="xs">
                    <Heading as="h1" size="headline-serif">The Ten Faces of Innovation</Heading>
                    <Text>
                      The key roles Clark identifies as essential for fostering innovation
                      across different contexts and teams.
                    </Text>
                  </Stack>

                  <Inline gap="sm" align="center">
                    <Text size="body-default" color="subtle">12 Lessons</Text>
                    <Text size="body-default" color="subtle" aria-hidden>·</Text>
                    <Text size="body-default" color="subtle">4 hours, 30min</Text>
                    <Text size="body-default" color="subtle" aria-hidden>·</Text>
                    <Text size="body-default" color="subtle">Certified</Text>
                  </Inline>

                  <Inline gap="sm">
                    <Badge label="Design" variant="outline" />
                    <Badge label="Design Thinking" variant="filled" />
                  </Inline>
                </Stack>
              </Stack>

              {/* ── Right column: course content accordion + CTA ── */}
              <Stack gap="md" style={{ flex: '1 0 0', minWidth: '34.5rem' }}>

                <Heading as="h2" size="subheader">Content</Heading>

                {/* CourseModuleList pattern: Accordion + show-more ghost Button (Layout/Examples/CourseModuleList) */}
                {/* showAll state slices ALL_MODULES; button label + icon reflect toggle state */}
                <div>
                  <Accordion>
                    {visibleModules.map((m) => (
                      <AccordionItem
                        key={m.title}
                        title={m.title}
                        subtitle={m.subtitle}
                        headingLevel={3}
                        defaultOpen={m.defaultOpen}
                      >
                        <Text>{m.body}</Text>
                      </AccordionItem>
                    ))}
                  </Accordion>
                  {hiddenCount > 0 && (
                    <Button
                      variant="ghost"
                      size="sm"
                      trailingIcon={showAll ? 'chevron-up' : 'chevron-down'}
                      onClick={() => setShowAll((prev) => !prev)}
                      style={{ marginLeft: 'var(--ds-space-inset-md)' }}
                    >
                      {showAll ? 'Show less' : `Show ${hiddenCount} more`}
                    </Button>
                  )}
                </div>

                {/* CTA row — Button metadata "form-actions-row" pattern */}
                <Inline justify="end" gap="sm">
                  <Button
                    variant="outlined"
                    shape="square"
                    icon="bookmark"
                    aria-label="Bookmark course"
                  />
                  <Button variant="default">Add to your cart</Button>
                </Inline>
              </Stack>

            </Inline>
          </Stack>
        </Box>
      </Box>

      {/* ── Section 2: Recommended courses ── */}
      <Box as="section" aria-labelledby="recommended-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            <Stack gap="sm">
              <Divider />
              <Heading id="recommended-heading" as="h2" size="headline">
                Recommended in Design Thinking
              </Heading>
            </Stack>

            {/* Carousel — full-width equal cards, page-based flip (Layout/Examples/Carousel → Discover pattern) */}
            {/* Each card: flex 1 0 min-content fills the row equally; PAGE_SIZE=4 per page */}
            <div style={{ display: 'flex', gap: 'var(--ds-grid-gutter)' }}>
              {visibleCourses.map((course, i) => (
                <div key={course.title} style={{ flex: '1 0 min-content' }}>
                  <CardVertical
                    thumbnailSrc={CARD_IMGS[i % CARD_IMGS.length]}
                    title={course.title}
                    duration={course.duration}
                    certified={course.certified}
                    size="lg"
                  />
                </div>
              ))}
            </div>

            {/* Paginator — counter + ButtonArrow pair; arrows flip a full page at a time */}
            <Inline gap="md" align="center">
              <Text size="body-default" color="subtle">
                {shownCount} of {RECOMMENDED_COURSES.length}
              </Text>
              <ButtonArrow
                direction="left"
                disabled={page === 0}
                onClick={() => setPage((p) => Math.max(0, p - 1))}
                aria-label="Previous"
              />
              <ButtonArrow
                direction="right"
                disabled={page === totalPages - 1}
                onClick={() => setPage((p) => Math.min(totalPages - 1, p + 1))}
                aria-label="Next"
              />
            </Inline>

          </Stack>
        </Box>
      </Box>

      {/* ── Section 3: Featured collection ── dark inverted background */}
      <Box
        as="section"
        aria-labelledby="collection-heading"
        paddingY="xxl"
        style={{ background: 'var(--ds-color-background-container-inverted)' }}
      >
        <Box className="container">
          <Inline wrap gap="lg" align="start">

            {/* ── Left: editorial promo ── */}
            <Box padding="xxl" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <Stack gap="lg">
                <Stack gap="md">
                  <Heading
                    id="collection-heading"
                    as="h2"
                    size="display"
                    style={{ color: 'var(--ds-color-text-inverted-default)' }}
                  >
                    Discover the Power of{' '}
                    <span style={{ color: 'var(--ds-color-accent-9)' }}>Beginner's Mind</span>
                  </Heading>
                  <Text style={{ color: 'var(--ds-color-text-inverted-default)' }}>
                    Beginner's mind means approaching life with openness and curiosity,
                    free from fixed ideas. Embrace learning with fresh eyes—explore how our
                    courses nurture this mindset and unlock new possibilities for your growth.
                  </Text>
                </Stack>
                <Button variant="default">See collection</Button>
              </Stack>
            </Box>

            {/* ── Right: related reading cards ── */}
            <Box padding="xxl" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <Stack gap="md">
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[0]}
                  thumbnailAlt="Zen Mind, Beginner's Mind book cover"
                  title="Zen Mind, Beginner's Mind"
                  duration="Shunryu Suzuki · 4 hours, 30min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[1]}
                  thumbnailAlt="Wherever You Go, There You Are book cover"
                  title="Wherever You Go, There You Are"
                  duration="Jon Kabat-Zinn · 2 hours, 15min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[2]}
                  thumbnailAlt="The Miracle of Mindfulness book cover"
                  title="The Miracle of Mindfulness"
                  duration="Thich Nhat Hanh · 1 hour, 10min"
                  variant="inverted"
                />
              </Stack>
            </Box>

          </Inline>
        </Box>
      </Box>

      {/* ── Footer ── grammar: <footer> landmark (contentinfo), one per page (ADR-011) */}
      {/* Uses logo-dark.svg (dark-background variant) from public/ */}
      <Box
        as="footer"
        style={{
          background: 'var(--ds-color-background-container-inverted)',
          borderTop: '1px solid var(--ds-color-border-inverted)',
        }}
      >
        <Box className="container" paddingY="md">
          <Inline justify="space-between" align="center">
            <img src="/logo-dark.svg" alt="UpSkill" height={32} width={84} />
            <Text size="body-small" style={{ color: 'var(--ds-color-text-inverted-subtle)' }}>
              Terms and Conditions
            </Text>
          </Inline>
        </Box>
      </Box>

    </Box>
  )
}
