// Course Overview page — /showcase/course
// Figma reference: node 96:5854 (Desktop)
// Generated by /layout-generation following ADR-011 landmark grammar.
//
// Pass 1 — Structure:  <main> → <header> → 3× <section> → <footer>
// Pass 2 — Components: AppHeader, Breadcrumb, VideoFrame, Accordion/AccordionItem,
//                      Badge, CardVertical, CardHorizontal, ButtonArrow, Button, Heading, Text
// Pass 3 — Spacing:    paddingY via Box inset tokens; gaps via Stack/Inline gap tokens

import {
  Accordion,
  AccordionItem,
  AppHeader,
  Badge,
  Box,
  Breadcrumb,
  Button,
  ButtonArrow,
  CardHorizontal,
  CardVertical,
  Divider,
  Heading,
  Inline,
  Stack,
  Text,
  VideoFrame,
} from '@upskill/components'

// ─── Sample data ─────────────────────────────────────────────────────────────
// Placeholder images — swap for real assets when wiring up the data layer
const VIDEO_SRC = 'https://picsum.photos/seed/tenfaces/740/413'
const CARD_IMGS = [
  'https://picsum.photos/seed/changebydesign/452/452',
  'https://picsum.photos/seed/creativeconfidence/452/452',
  'https://picsum.photos/seed/designeveryday/452/452',
  'https://picsum.photos/seed/designthinking/452/452',
]
const BOOK_IMGS = [
  'https://picsum.photos/seed/zenmin/80/80',
  'https://picsum.photos/seed/whereveryougo/80/80',
  'https://picsum.photos/seed/miraclemindful/80/80',
]

export default function CourseOverview() {
  return (
    // ── Page ── grammar: exactly one <main> per route (ADR-011)
    <Box as="main">

      {/* ── Header ── grammar: AppHeader satisfies the banner/navigation landmark */}
      {/* AppHeader renders its own <nav aria-label="Main navigation"> internally */}
      <AppHeader
        logoSrc="/logo.svg"
        logoSrcDark="/logo-dark.svg"
        logoAlt="UpSkill"
        navItems={[
          { label: 'All Courses', href: '/courses' },
          { label: 'My Courses', href: '/my-courses', active: true },
        ]}
        userName="Sarah"
      />

      {/* ── Section 1: Course overview ── aria-label because there is no visible section-level heading */}
      {/* grammar: <Box as="section"> + paddingY rhythm token (ADR-011) */}
      <Box as="section" aria-label="Course overview" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            {/* Breadcrumb — usage.when: "page is deep in a navigation hierarchy" */}
            {/* Breadcrumb renders its own <nav aria-label="Breadcrumb"> */}
            <Breadcrumb
              items={[
                { label: 'Home', href: '/' },
                { label: 'Courses', href: '/courses' },
                { label: 'Course Overview' },
              ]}
            />

            {/* Columns — grammar: Inline wrap for two-panel layout that stacks on mobile */}
            {/* Each child: flex: 1 0 0 fills equally; minWidth: 34.5rem (~552px) sets stack breakpoint */}
            <Inline wrap align="start" gap="lg">

              {/* ── Left column: video + course description ── */}
              <Stack gap="md" style={{ flex: '1 0 0', minWidth: '34.5rem' }}>

                {/* VideoFrame — usage.when: "displaying a video thumbnail with play overlay" */}
                {/* composition.containedBy: Stack */}
                <VideoFrame src={VIDEO_SRC} alt="The Ten Faces of Innovation — course preview" />

                <Stack gap="sm">
                  {/* Author — typography rule: visible text through Text; link as HTML intrinsic <a> inside Text */}
                  <Text size="body-default" color="subtle">
                    <a
                      href="#"
                      style={{ color: 'var(--ds-color-text-link-default)', fontWeight: 600, textDecoration: 'underline' }}
                    >
                      Edward Clark
                    </a>
                    {', Author and educator, MICA'}
                  </Text>

                  <Stack gap="xs">
                    {/* Course title — typography rule: Heading for all headings; serif for editorial impact */}
                    <Heading as="h1" size="headline-serif">The Ten Faces of Innovation</Heading>
                    {/* Course description — typography rule: Text, never raw string or <p> */}
                    <Text>
                      The key roles Clark identifies as essential for fostering innovation
                      across different contexts and teams.
                    </Text>
                  </Stack>

                  {/* Metadata row — Inline: horizontal row of dot-separated facts */}
                  {/* usage.patterns: "metadata-row" from Text/Icon metadata */}
                  <Inline gap="sm" align="center">
                    <Text size="body-default" color="subtle">12 Lessons</Text>
                    <Text size="body-default" color="subtle" aria-hidden>·</Text>
                    <Text size="body-default" color="subtle">4 hours, 30min</Text>
                    <Text size="body-default" color="subtle" aria-hidden>·</Text>
                    {/* Badge-check icon — Icon inherits color via currentColor; color set on parent Inline */}
                    <Inline gap="xs" align="center">
                      <Text size="body-default" color="subtle">Certified</Text>
                    </Inline>
                  </Inline>

                  {/* Badge list — Inline; Badge.containedBy includes Inline */}
                  <Inline gap="sm">
                    {/* Badge variant="outline" — default, minimal border */}
                    <Badge label="Design" variant="outline" />
                    {/* Badge variant="filled" — selected/highlighted category */}
                    <Badge label="Design Thinking" variant="filled" />
                  </Inline>
                </Stack>
              </Stack>

              {/* ── Right column: course content accordion + CTA ── */}
              <Stack gap="md" style={{ flex: '1 0 0', minWidth: '34.5rem' }}>

                {/* Section sub-heading — typography rule: Heading not raw string */}
                <Heading as="h2" size="subheader">Content</Heading>

                {/* Accordion — usage.when: "progressive disclosure of a structured content list" */}
                {/* composition.containedBy: Stack; AccordionItem.headingLevel=3 (child of h2 above) */}
                <Accordion>
                  <AccordionItem title="The Anthropologist" subtitle="4 hours, 30min" headingLevel={3}>
                    Observes human behaviour to find inspiration and identify opportunities for innovation.
                  </AccordionItem>
                  <AccordionItem title="The Experimenter" subtitle="4 hours, 30min" headingLevel={3} defaultOpen>
                    The Experimenter is a curious, hands-on innovator who learns by testing and prototyping.
                    They take calculated risks, embrace failure as learning, and drive innovation through
                    rapid iteration and experimentation.
                  </AccordionItem>
                  <AccordionItem title="The Cross-Pollinator" subtitle="4 hours, 30min" headingLevel={3}>
                    Draws connections across industries, cultures, and disciplines to spark new ideas.
                  </AccordionItem>
                  <AccordionItem title="The Hurdler" subtitle="4 hours, 30min" headingLevel={3}>
                    Thrives on constraints, turning obstacles and setbacks into competitive advantages.
                  </AccordionItem>
                  <AccordionItem title="The Collaborator" subtitle="4 hours, 30min" headingLevel={3}>
                    Brings diverse teams together, bridging silos to co-create breakthroughs.
                  </AccordionItem>
                  <AccordionItem title="The Director" subtitle="4 hours, 30min" headingLevel={3}>
                    Assembles talented casts and sets the stage for creative work to flourish.
                  </AccordionItem>
                </Accordion>

                {/* Show more — Button ghost variant; Phase 5d: ghost replaces standalone ShowMoreLink */}
                {/* trailingIcon provides the chevron direction cue (Button metadata: "directional cues") */}
                <Button variant="ghost" trailingIcon="chevron-down">Show more</Button>

                {/* CTA row — Inline: "form-actions-row" pattern from Button metadata; justify="end" */}
                <Inline justify="end" gap="sm">
                  {/* Icon-only bookmark button — Button.shape="square" + icon prop (Button metadata) */}
                  <Button
                    variant="outlined"
                    shape="square"
                    icon="bookmark"
                    aria-label="Bookmark course"
                  />
                  {/* Primary CTA — Button.variant="default" for primary actions */}
                  <Button variant="default">Add to your cart</Button>
                </Inline>
              </Stack>

            </Inline>
          </Stack>
        </Box>
      </Box>

      {/* ── Section 2: Recommended courses ── aria-labelledby → Heading id below */}
      {/* grammar: <Box as="section"> + paddingY; Heading.id anchors the labelledby */}
      <Box as="section" aria-labelledby="recommended-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            {/* Section heading — id anchors aria-labelledby on the section above */}
            {/* Divider + Heading replicates the HeadlineRow pattern from Figma */}
            <Stack gap="sm">
              <Divider />
              {/* typography rule: Heading, never raw string */}
              <Heading id="recommended-heading" as="h2" size="headline">
                Recommended in Design Thinking
              </Heading>
            </Stack>

            {/* Card carousel — grammar: Inline wrap for equal-width cards that reflow on mobile */}
            {/* Each card: flex: 1 0 0 fills space equally; minWidth: 250px sets one-column breakpoint */}
            {/* CardVertical.containedBy: Inline (composition rule) */}
            <Inline wrap gap="lg" align="start">
              <CardVertical
                thumbnailSrc={CARD_IMGS[0]}
                title="Change by Design"
                duration="12 Hours"
                certified
                style={{ flex: '1 0 0', minWidth: '250px' }}
              />
              <CardVertical
                thumbnailSrc={CARD_IMGS[1]}
                title="Creative Confidence"
                duration="12 Hours"
                certified
                style={{ flex: '1 0 0', minWidth: '250px' }}
              />
              <CardVertical
                thumbnailSrc={CARD_IMGS[2]}
                title="The Design of Everyday Things"
                duration="12 Hours"
                certified
                style={{ flex: '1 0 0', minWidth: '250px' }}
              />
              <CardVertical
                thumbnailSrc={CARD_IMGS[3]}
                title="The Design Thinking Playbook"
                duration="12 Hours"
                certified
                style={{ flex: '1 0 0', minWidth: '250px' }}
              />
            </Inline>

            {/* Paginator — Inline: counter Text + ButtonArrow pair */}
            {/* ButtonArrow.direction is required; disabled via HTML attribute (ButtonHTMLAttributes spread) */}
            <Inline gap="md" align="center">
              <Text size="body-default" color="subtle">4 of 8</Text>
              <ButtonArrow direction="left" disabled aria-label="Previous page" />
              <ButtonArrow direction="right" aria-label="Next page" />
            </Inline>

          </Stack>
        </Box>
      </Box>

      {/* ── Section 3: Featured collection ── dark inverted background */}
      {/* var() token reference for background — allowed by inline-style reconciliation (ADR-011) */}
      <Box
        as="section"
        aria-labelledby="collection-heading"
        paddingY="xxl"
        style={{ background: 'var(--ds-color-background-container-inverted)' }}
      >
        <Box className="container">

          {/* Two-column layout — grammar: Inline wrap for side-by-side columns that stack on mobile */}
          <Inline wrap gap="lg" align="start">

            {/* ── Left: editorial promo ── */}
            <Stack gap="lg" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <Stack gap="md">
                {/* Multi-color heading — inline <span> with var() token for teal highlight */}
                {/* var() reference is allowed (not a raw color value) */}
                <Heading
                  id="collection-heading"
                  as="h2"
                  size="display"
                  style={{ color: 'var(--ds-color-text-inverted-default)' }}
                >
                  Discover the Power of{' '}
                  <span style={{ color: 'var(--ds-color-accent-9)' }}>Beginner's Mind</span>
                </Heading>
                <Text style={{ color: 'var(--ds-color-text-inverted-subtle)' }}>
                  Beginner's mind means approaching life with openness and curiosity,
                  free from fixed ideas. Embrace learning with fresh eyes—explore how our
                  courses nurture this mindset and unlock new possibilities for your growth.
                </Text>
              </Stack>
              {/* CTA — Button.variant="default" for primary action */}
              <Button variant="default">See collection</Button>
            </Stack>

            {/* ── Right: related reading cards ── */}
            {/* CardHorizontal.variant="inverted" — applies inverted text colours */}
            <Stack gap="md" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <CardHorizontal
                thumbnailSrc={BOOK_IMGS[0]}
                thumbnailAlt="Zen Mind, Beginner's Mind book cover"
                title="Zen Mind, Beginner's Mind"
                duration="Shunryu Suzuki · 4 hours, 30min"
                variant="inverted"
              />
              <CardHorizontal
                thumbnailSrc={BOOK_IMGS[1]}
                thumbnailAlt="Wherever You Go, There You Are book cover"
                title="Wherever You Go, There You Are"
                duration="Jon Kabat-Zinn · 2 hours, 15min"
                variant="inverted"
              />
              <CardHorizontal
                thumbnailSrc={BOOK_IMGS[2]}
                thumbnailAlt="The Miracle of Mindfulness book cover"
                title="The Miracle of Mindfulness"
                duration="Thich Nhat Hanh · 1 hour, 10min"
                variant="inverted"
              />
            </Stack>

          </Inline>
        </Box>
      </Box>

      {/* ── Footer ── grammar: <footer> landmark (contentinfo), one per page (ADR-011) */}
      <Box
        as="footer"
        style={{
          background: 'var(--ds-color-background-container-inverted)',
          borderTop: '1px solid var(--ds-color-border-inverted)',
        }}
      >
        <Box className="container" paddingY="md">
          {/* Logo + legal — Inline justify="between": space-between the two groups */}
          <Inline justify="space-between" align="center">
            {/* Logo placeholder — img is an HTML intrinsic (allowed); swap for real SVG asset */}
            <img src="/logo-mono.svg" alt="UpSkill" height={32} width={84} />
            {/* typography rule: Text for visible UI text */}
            <Text size="body-small" style={{ color: 'var(--ds-color-text-inverted-subtle)' }}>
              Terms and Conditions
            </Text>
          </Inline>
        </Box>
      </Box>

    </Box>
  )
}
