// Homepage page — /showcase/
// Figma reference: node 96:6110 "Home" (Desktop 96:6110, Tablet 96:6147, Mobile 96:6184)
// Generated by /layout-generation following ADR-011 landmark grammar.
// Header, Section 4 (Featured collection), and Footer are reused verbatim from UserSettings.tsx.
// Section 3 (Discover new courses carousel) reuses the Recommended Courses carousel pattern
// and data from CourseOverview.tsx, plus a Chip filter row per the Figma "Chip carrousel row".
//
// Pass 1 — Structure:  <main> → AppHeader → 4× <section> → <footer>
// Pass 2 — Components: AppHeader, Breadcrumb, VideoFrame, ProgressBar, ButtonArrow, Divider,
//                      CardVertical, Chip, CardHorizontal, Button, Heading, Text
// Pass 3 — Spacing:    paddingY via Box inset tokens; gaps via Stack/Inline gap tokens

import { useState } from 'react'
import {
  AppHeader,
  Box,
  Breadcrumb,
  Button,
  ButtonArrow,
  CardHorizontal,
  CardVertical,
  Chip,
  Divider,
  Heading,
  Inline,
  ProgressBar,
  Stack,
  Text,
  VideoFrame,
  useCarousel,
} from '@upskill/components'

// ─── Sample data ─────────────────────────────────────────────────────────────
// public/ assets need the Vite base prefix to resolve under GitHub Pages
const BASE = import.meta.env.BASE_URL
const VIDEO_SRC = `${BASE}course-video-image-example.png`
const CARD_IMGS = [
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
]
const BOOK_IMGS = [
  'https://picsum.photos/seed/zenmin/80/80',
  'https://picsum.photos/seed/whereveryougo/80/80',
  'https://picsum.photos/seed/miraclemindful/80/80',
]

// Stepper — three chapters of "The Ten Faces of Innovation", reusing the module
// names/body copy already established in CourseOverview's ALL_MODULES list.
const CHAPTERS = [
  {
    title: 'Chapter 1: The Experimenter',
    body: 'Focuses on prototyping, testing, and learning through trial and error. This persona encourages rapid experimentation to discover effective solutions by embracing failure as part of the innovation process. Experimenters are curious risk-takers who use data and feedback to refine ideas continuously and foster a culture of innovation through hands-on learning.',
    progress: 25,
  },
  {
    title: 'Chapter 2: The Cross-Pollinator',
    body: 'Draws connections across industries, cultures, and disciplines to spark new ideas.',
    progress: 55,
  },
  {
    title: 'Chapter 3: The Hurdler',
    body: 'Thrives on constraints, turning obstacles and setbacks into competitive advantages.',
    progress: 90,
  },
]

const SAVED_COURSES = [
  { title: 'Color Theory II', duration: '2 Hours left', progress: 26, thumbnailSrc: CARD_IMGS[0] },
  { title: 'Heuristics Evaluation', duration: '4 Hours left', progress: 26, thumbnailSrc: CARD_IMGS[1] },
  { title: 'Creative Acts for Curious People', duration: '12 Hours', thumbnailSrc: CARD_IMGS[2] },
  { title: 'Systems Thinking', duration: '12 Hours', thumbnailSrc: CARD_IMGS[3] },
]

const DISCOVER_FILTERS = ['Communication', 'UX', 'Usability', 'Design Thinking']

const DISCOVER_COURSES = [
  { title: 'Change by Design', duration: '12 Hours', certified: true, category: 'Design Thinking' },
  { title: 'Creative Confidence', duration: '12 Hours', certified: true, category: 'Design Thinking' },
  { title: 'The Design Thinking Playbook', duration: '12 Hours', certified: true, category: 'Design Thinking' },
  { title: 'Designing for Growth', duration: '9 Hours', certified: true, category: 'Design Thinking' },
  { title: 'The Design of Everyday Things', duration: '12 Hours', certified: true, category: 'UX' },
  { title: 'Sprint', duration: '6 Hours', certified: true, category: 'UX' },
  { title: "Don't Make Me Think", duration: '5 Hours', certified: true, category: 'UX' },
  { title: '100 Things Every Designer Needs to Know About People', duration: '7 Hours', certified: true, category: 'UX' },
  { title: 'Creative Acts for Curious People', duration: '10 Hours', certified: true, category: 'Usability' },
  { title: 'Rocket Surgery Made Easy', duration: '6 Hours', certified: true, category: 'Usability' },
  { title: 'A Project Guide to UX Design', duration: '8 Hours', certified: true, category: 'Usability' },
  { title: 'Lean UX', duration: '7 Hours', certified: true, category: 'Usability' },
  { title: 'The Art of Innovation', duration: '8 Hours', certified: true, category: 'Communication' },
  { title: 'Thinking, Fast and Slow', duration: '14 Hours', certified: true, category: 'Communication' },
  { title: 'Crucial Conversations', duration: '9 Hours', certified: true, category: 'Communication' },
  { title: 'Made to Stick', duration: '6 Hours', certified: true, category: 'Communication' },
]

const SAVED_CARD_WIDTH = 260
// One less than SAVED_COURSES.length — itemCount === visibleCount would make
// useCarousel's maxOffset permanently 0, disabling the arrows even when a
// narrower viewport clips a card that overflow:hidden hides.
const SAVED_VISIBLE_COUNT = 3
const DISCOVER_CARD_WIDTH = 280
const DISCOVER_VISIBLE_COUNT = 4

export default function Homepage() {
  const [chapter, setChapter] = useState(0)
  const [activeFilter, setActiveFilter] = useState(DISCOVER_FILTERS[0])

  const savedCarousel = useCarousel(SAVED_COURSES.length, SAVED_VISIBLE_COUNT)

  const filteredDiscoverCourses = DISCOVER_COURSES.filter((course) => course.category === activeFilter)
  const discoverCarousel = useCarousel(filteredDiscoverCourses.length, DISCOVER_VISIBLE_COUNT)

  const currentChapter = CHAPTERS[chapter]

  const selectFilter = (filter: string) => {
    setActiveFilter(filter)
    discoverCarousel.reset()
  }

  return (
    // ── Page ── grammar: exactly one <main> per route (ADR-011)
    <Box as="main">

      {/* ── Header ── reused verbatim from UserSettings.tsx */}
      <AppHeader
        logoSrc={`${BASE}logo.svg`}
        logoSrcDark={`${BASE}logo-dark.svg`}
        logoAlt="UpSkill"
        navItems={[
          { label: 'All Courses', href: '/courses' },
          { label: 'My Courses', href: '/my-courses', active: true },
        ]}
        userAvatarSrc="https://placehold.co/24x24/D15D50/ffffff?text=S"
        userName="Sarah"
        userMenuItems={[
          { value: 'profile', label: 'My Profile' },
          { value: 'settings', label: 'Settings' },
          { value: 'logout', label: 'Log out' },
        ]}
      />

      {/* ── Section 1: Course ── aria-labelledby points to the visible welcome heading */}
      <Box as="section" aria-labelledby="welcome-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            {/* Breadcrumb renders its own <nav aria-label="Breadcrumb"> */}
            <Breadcrumb
              items={[
                { label: 'Home', href: '/' },
                { label: 'Profile' },
              ]}
            />

            <Stack gap="xs">
              <Heading id="welcome-heading" as="h1" size="headline">Welcome back, Sarah</Heading>
              <Text>Continue learning, discover new courses!</Text>
            </Stack>

            {/* Two-panel — grammar: Inline wrap; each child grow=1 + minWidth sets stack breakpoint */}
            <Inline wrap align="start" gap="lg">

              {/* ── Left column: video ── VideoFrame usage.when: "displaying a video course preview" */}
              <Stack grow={1} minWidth="34.5rem">
                <VideoFrame src={VIDEO_SRC} alt="The Ten Faces of Innovation — course preview" />
              </Stack>

              {/* ── Right column: chapter stepper ── interactive 3-step navigator over CHAPTERS */}
              <Stack gap="md" grow={1} minWidth="34.5rem">
                <Stack gap="sm">
                  <Heading as="h2" size="headline-serif">The 10 Faces of Innovation:</Heading>
                  <ProgressBar value={currentChapter.progress} label="Course progress" />
                </Stack>

                <Stack gap="md">
                  {/* Fixed minHeight reserves space for the longest chapter body so the
                      paginator row below never shifts vertically as chapter content changes */}
                  <Stack gap="xs" minHeight="10rem">
                    <Heading as="h3" size="subheader">{currentChapter.title}</Heading>
                    <Text>{currentChapter.body}</Text>
                  </Stack>

                  {/* ButtonArrow usage.when: "stepping through chapters or slides in a sequence" */}
                  <Inline fullWidth gap="md" align="center" justify="end">
                    <Text size="metadata" color="subtle">{`Chapter ${chapter + 1} of ${CHAPTERS.length}`}</Text>
                    <ButtonArrow
                      direction="left"
                      disabled={chapter === 0}
                      onClick={() => setChapter((c) => c - 1)}
                      aria-label="Previous chapter"
                    />
                    <ButtonArrow
                      direction="right"
                      disabled={chapter === CHAPTERS.length - 1}
                      onClick={() => setChapter((c) => c + 1)}
                      aria-label="Next chapter"
                    />
                  </Inline>
                </Stack>
              </Stack>

            </Inline>
          </Stack>
        </Box>
      </Box>

      {/* ── Section 2: Saved courses ── CardVertical usage.patterns "saved-courses-carousel": size=sm + progress */}
      <Box as="section" aria-labelledby="saved-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            <Stack gap="sm">
              <Divider />
              <Heading id="saved-heading" as="h2" size="headline">Saved Courses</Heading>
            </Stack>

            {/* Carousel — Box clips track; .carousel-outer switches to native scroll on mobile */}
            <Box overflow="hidden" className="carousel-outer">
              <div
                style={{
                  display: 'flex',
                  gap: 'var(--ds-grid-gutter)',
                  transform: `translateX(calc(-${savedCarousel.offset} * (${SAVED_CARD_WIDTH}px + var(--ds-grid-gutter))))`,
                  transition: 'transform 300ms ease',
                }}
              >
                {SAVED_COURSES.map((course) => (
                  <div key={course.title} style={{ flexShrink: 0, width: `${SAVED_CARD_WIDTH}px`, scrollSnapAlign: 'start' }}>
                    <CardVertical
                      thumbnailSrc={course.thumbnailSrc}
                      title={course.title}
                      duration={course.duration}
                      progress={course.progress}
                      size="sm"
                    />
                  </div>
                ))}
              </div>
            </Box>

            <Inline gap="sm" justify="end" className="hide-on-mobile">
              <ButtonArrow direction="left" disabled={!savedCarousel.canPrev} onClick={savedCarousel.prev} aria-label="Previous" />
              <ButtonArrow direction="right" disabled={!savedCarousel.canNext} onClick={savedCarousel.next} aria-label="Next" />
            </Inline>

          </Stack>
        </Box>
      </Box>

      {/* ── Section 3: Discover new courses ── Chip usage.patterns "filter-bar" + CardVertical size=lg carousel */}
      <Box as="section" aria-labelledby="discover-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            <Heading id="discover-heading" as="h2" size="headline">Discover new courses</Heading>

            <Inline gap="sm" wrap>
              {DISCOVER_FILTERS.map((filter) => (
                <Chip
                  key={filter}
                  selected={filter === activeFilter}
                  onClick={() => selectFilter(filter)}
                >
                  {filter}
                </Chip>
              ))}
            </Inline>

            <Box overflow="hidden" className="carousel-outer">
              <div
                style={{
                  display: 'flex',
                  gap: 'var(--ds-grid-gutter)',
                  transform: `translateX(calc(-${discoverCarousel.offset} * (${DISCOVER_CARD_WIDTH}px + var(--ds-grid-gutter))))`,
                  transition: 'transform 300ms ease',
                }}
              >
                {filteredDiscoverCourses.map((course, i) => (
                  <div key={course.title} style={{ flexShrink: 0, width: `${DISCOVER_CARD_WIDTH}px`, scrollSnapAlign: 'start' }}>
                    <CardVertical
                      thumbnailSrc={CARD_IMGS[i % CARD_IMGS.length]}
                      title={course.title}
                      duration={course.duration}
                      certified={course.certified}
                      size="lg"
                    />
                  </div>
                ))}
              </div>
            </Box>

            <Inline gap="sm" justify="end" className="hide-on-mobile">
              <ButtonArrow direction="left" disabled={!discoverCarousel.canPrev} onClick={discoverCarousel.prev} aria-label="Previous" />
              <ButtonArrow direction="right" disabled={!discoverCarousel.canNext} onClick={discoverCarousel.next} aria-label="Next" />
            </Inline>

          </Stack>
        </Box>
      </Box>

      {/* ── Section 4: Featured collection ── reused verbatim from UserSettings.tsx (dark inverted background) */}
      <Box
        as="section"
        aria-labelledby="collection-heading"
        paddingY="xxl"
        background="inverted"
      >
        <Box className="container">
          <Inline wrap gap="lg" align="start">

            {/* ── Left: editorial promo ── */}
            <Box padding="xxl" grow={1} minWidth="20rem">
              <Stack gap="lg">
                <Stack gap="md">
                  <Heading
                    id="collection-heading"
                    as="h2"
                    size="display"
                    color="inverted"
                  >
                    Discover the Power of{' '}
                    <Text as="span" size="inherit" color="accent-inverted">Beginner's Mind</Text>
                  </Heading>
                  <Text color="inverted">
                    Beginner's mind means approaching life with openness and curiosity,
                    free from fixed ideas. Embrace learning with fresh eyes—explore how our
                    courses nurture this mindset and unlock new possibilities for your growth.
                  </Text>
                </Stack>
                <Button variant="default">See collection</Button>
              </Stack>
            </Box>

            {/* ── Right: related reading cards ── */}
            <Box padding="xxl" grow={1} minWidth="20rem">
              <Stack gap="md">
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[0]}
                  thumbnailAlt="Zen Mind, Beginner's Mind book cover"
                  title="Zen Mind, Beginner's Mind"
                  duration="Shunryu Suzuki · 4 hours, 30min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[1]}
                  thumbnailAlt="Wherever You Go, There You Are book cover"
                  title="Wherever You Go, There You Are"
                  duration="Jon Kabat-Zinn · 2 hours, 15min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[2]}
                  thumbnailAlt="The Miracle of Mindfulness book cover"
                  title="The Miracle of Mindfulness"
                  duration="Thich Nhat Hanh · 1 hour, 10min"
                  variant="inverted"
                />
              </Stack>
            </Box>

          </Inline>
        </Box>
      </Box>

      {/* ── Footer ── reused verbatim from UserSettings.tsx */}
      <Box
        as="footer"
        background="inverted"
        style={{ borderTop: '1px solid var(--ds-color-border-inverted)' }}
      >
        <Box className="container" paddingY="md">
          <Inline justify="space-between" align="center">
            <img src={`${BASE}logo-dark.svg`} alt="UpSkill" height={32} width={84} />
            <Text size="body-small" color="inverted-subtle">
              Terms and Conditions
            </Text>
          </Inline>
        </Box>
      </Box>

    </Box>
  )
}
