// User Settings page — /showcase/settings
// Figma reference: node 96:6221 "User Settings" (Desktop 96:6222, Tablet 96:6270, Mobile 96:6318)
// Generated by /layout-generation following ADR-011 landmark grammar.
// Header, Section 3 (Featured collection), and Footer are reused verbatim from CourseOverview.tsx.
//
// Pass 1 — Structure:  <main> → AppHeader → 2× <section> → <footer>
// Pass 2 — Components: AppHeader, Breadcrumb, Card, Avatar, TextField, Select, Button, Divider,
//                      Checkbox, Icon, CardHorizontal, Heading, Text
// Pass 3 — Spacing:    paddingY via Box inset tokens; gaps via Stack/Inline gap tokens

import { useEffect, useState } from 'react'
import {
  Avatar,
  AppHeader,
  Box,
  Breadcrumb,
  Button,
  Card,
  CardHorizontal,
  Checkbox,
  Divider,
  Heading,
  Icon,
  Inline,
  Select,
  Stack,
  Text,
  TextField,
} from '@upskill/components'
import styles from './UserSettings.module.css'

// ─── Sample data ─────────────────────────────────────────────────────────────
// public/ assets need the Vite base prefix to resolve under GitHub Pages
const BASE = import.meta.env.BASE_URL
const CARD_IMGS = [
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
  `${BASE}image-placeholder.png`,
]
const BOOK_IMGS = [
  'https://picsum.photos/seed/zenmin/80/80',
  'https://picsum.photos/seed/whereveryougo/80/80',
  'https://picsum.photos/seed/miraclemindful/80/80',
]

const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English' },
  { value: 'es', label: 'Spanish' },
  { value: 'fr', label: 'French' },
]

const ACHIEVEMENTS = [
  { title: 'Color Theory', category: 'Graphic Design', icon: 'pen-tool' as const, tier: 'silver' as const },
  { title: 'Effective Communication', category: 'Soft Skills', icon: 'zap' as const, tier: 'gold' as const },
]

const STARTED_COURSES = [
  { title: 'Color Theory II', duration: '4 hours, 30min', progress: 12, thumbnailSrc: CARD_IMGS[0] },
  { title: 'Heuristics Evaluation', duration: '4 hours, 30min', progress: 55, thumbnailSrc: CARD_IMGS[1] },
]

const SAVED_COURSES = [
  { title: 'Systems Thinking', duration: '4 hours, 30min', thumbnailSrc: CARD_IMGS[2] },
  { title: 'Creative Acts for Curious People', duration: '4 hours, 30min', thumbnailSrc: CARD_IMGS[3] },
]

export default function UserSettings() {
  const [isDark, setIsDark] = useState(false)

  useEffect(() => {
    document.documentElement.dataset.theme = isDark ? 'dark' : 'light'
    return () => {
      document.documentElement.dataset.theme = 'light'
    }
  }, [isDark])

  return (
    // ── Page ── grammar: exactly one <main> per route (ADR-011)
    <Box as="main">

      {/* ── Header ── reused verbatim from CourseOverview.tsx */}
      <AppHeader
        logoSrc={`${BASE}logo.svg`}
        logoSrcDark={`${BASE}logo-dark.svg`}
        logoAlt="UpSkill"
        navItems={[
          { label: 'All Courses', href: '/courses' },
          { label: 'My Courses', href: '/my-courses', active: true },
        ]}
        userAvatarSrc="https://placehold.co/24x24/D15D50/ffffff?text=S"
        userName="Sarah"
        userMenuItems={[
          { value: 'profile', label: 'My Profile' },
          { value: 'settings', label: 'Settings' },
          { value: 'logout', label: 'Log out' },
        ]}
      />

      {/* ── Section 1: Profile details ── aria-labelledby points to the visible page heading */}
      <Box as="section" aria-labelledby="profile-details-heading" paddingY="lg">
        <Box className="container">
          <Stack gap="md">

            {/* Breadcrumb renders its own <nav aria-label="Breadcrumb"> */}
            <Breadcrumb
              items={[
                { label: 'Home', href: '/' },
                { label: 'User Settings' },
              ]}
            />

            <Heading id="profile-details-heading" as="h1" size="headline">Profile Details</Heading>

            {/* Two-panel — grammar: Inline wrap; left column weighted 2:1 over the sidebar, both share the
                same minWidth so the pair wraps to a single column together, matching the Tablet/Mobile Figma frames */}
            <Inline wrap align="start" gap="lg">

              {/* ── Left column: profile form + account settings ── */}
              {/* align="stretch" overrides the flex-start inherited from the parent Inline's --_align
                  custom property, so the Cards below fill this column's full width */}
              <Stack gap="xl" align="stretch" style={{ flex: '2 0 0', minWidth: '20rem' }}>

                {/* User Form card — usage.patterns "form-section": Card > Stack > [TextField, TextField, ...]
                    background transparent per design: Card only supplies the border/padding here, not a fill */}
                <Card padding="lg" className={styles.transparentCard}>
                  {/* Inner Inline wraps independently at a higher minWidth, matching the Tablet/Mobile
                      Figma frames where the avatar block stacks above the fields inside the same card.
                      justify="center" centers the avatar block on its own wrapped line at tablet/mobile;
                      it's a no-op at desktop and on the form-fields block, which already fills its line
                      via flex: 1 0 0 */}
                  <Inline wrap align="start" justify="center" gap="md">
                    <Stack gap="sm" align="center" style={{ minWidth: '13rem' }}>
                      {/* Avatar usage.patterns "profile-header": Stack > [Avatar(lg), Stack > [Heading, Text]] */}
                      <Avatar src="https://picsum.photos/seed/sarahjones/128/128" alt="Sarah Jones" size="lg" />
                      <Stack gap="xs" align="center">
                        <Heading as="h2" size="title-small">Sarah Jones</Heading>
                        <Text size="body-small" color="subtle">Product Designer</Text>
                      </Stack>
                    </Stack>

                    {/* align="stretch" so each TextField's root fills this column instead of shrinking to its input's content width */}
                    <Stack gap="lg" align="stretch" style={{ flex: '1 0 0', minWidth: '18rem' }}>
                      <TextField label="Name" defaultValue="Sarah" />
                      <TextField label="Surname" defaultValue="Jones" />
                      <TextField label="Job Title" defaultValue="Product Designer" />
                    </Stack>
                  </Inline>
                </Card>

                {/* Account Settings */}
                <Stack gap="md">
                  <Heading as="h2" size="headline">Account Settings</Heading>
                  <Card padding="lg" className={styles.transparentCard}>
                    <Stack gap="lg">
                      <Inline wrap gap="lg">
                        <Box style={{ minWidth: '15rem' }}>
                          <Select label="Language" options={LANGUAGE_OPTIONS} defaultValue="en" />
                        </Box>
                        <Stack gap="sm">
                          <Text as="label" size="label" color="subtle" htmlFor="theme-toggle">Theme</Text>
                          {/* No Switch/Toggle in the fixed set — Button reproduces the Figma ButtonToggle's
                              outlined+icon+label styling exactly */}
                          <Button
                            id="theme-toggle"
                            variant="outlined"
                            icon={isDark ? 'moon-star' : 'sun'}
                            aria-pressed={isDark}
                            onClick={() => setIsDark((prev) => !prev)}
                          >
                            {isDark ? 'Dark' : 'Light'}
                          </Button>
                        </Stack>
                      </Inline>

                      <Divider />

                      <Stack gap="md">
                        <Heading as="h3" size="title-small">Email Subscriptions</Heading>
                        {/* Checkbox usage.patterns "notification-preferences" */}
                        <Stack gap="sm">
                          <Checkbox label="Weekly Newsletter" />
                          <Checkbox label="New course announcements" defaultChecked />
                        </Stack>
                      </Stack>
                    </Stack>
                  </Card>
                </Stack>

                {/* Button metadata "form-actions" pattern (single primary action) */}
                <Inline justify="start">
                  <Button variant="default">Save</Button>
                </Inline>
              </Stack>

              {/* ── Right column: achievements + course lists sidebar ── */}
              <Stack gap="xxl" style={{ flex: '1 0 0', minWidth: '20rem', maxWidth: '23rem' }}>

                <Stack gap="md">
                  <Heading as="h2" size="subheader">Achievements</Heading>
                  <Stack gap="md">
                    {ACHIEVEMENTS.map((a) => (
                      <Inline key={a.title} gap="md" align="start">
                        <Box
                          className={[
                            styles.achievementIcon,
                            a.tier === 'gold' ? styles.achievementIconGold : styles.achievementIconSilver,
                          ].join(' ')}
                        >
                          <Icon name={a.icon} size="md" />
                        </Box>
                        <Stack gap="xs">
                          <Heading as="h3" size="title-small">{a.title}</Heading>
                          <Text size="metadata" color="brand">{a.category}</Text>
                        </Stack>
                      </Inline>
                    ))}
                  </Stack>
                  <Button variant="outlined" size="sm" icon="download">Download All Certificates</Button>
                </Stack>

                {/* CardHorizontal usage.patterns "started-courses-list" */}
                <Stack gap="md">
                  <Heading as="h2" size="subheader">Started Courses</Heading>
                  <Stack gap="md">
                    {STARTED_COURSES.map((c) => (
                      <CardHorizontal
                        key={c.title}
                        thumbnailSrc={c.thumbnailSrc}
                        thumbnailAlt=""
                        title={c.title}
                        duration={c.duration}
                        certified
                        progress={c.progress}
                      />
                    ))}
                  </Stack>
                </Stack>

                <Stack gap="md">
                  <Heading as="h2" size="subheader">Saved Courses</Heading>
                  <Stack gap="md">
                    {SAVED_COURSES.map((c) => (
                      <CardHorizontal
                        key={c.title}
                        thumbnailSrc={c.thumbnailSrc}
                        thumbnailAlt=""
                        title={c.title}
                        duration={c.duration}
                        certified
                      />
                    ))}
                  </Stack>
                </Stack>

              </Stack>

            </Inline>
          </Stack>
        </Box>
      </Box>

      {/* ── Section 2: Featured collection ── reused verbatim from CourseOverview.tsx (dark inverted background) */}
      <Box
        as="section"
        aria-labelledby="collection-heading"
        paddingY="xxl"
        style={{ background: 'var(--ds-color-background-container-inverted)' }}
      >
        <Box className="container">
          <Inline wrap gap="lg" align="start">

            {/* ── Left: editorial promo ── */}
            <Box padding="xxl" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <Stack gap="lg">
                <Stack gap="md">
                  <Heading
                    id="collection-heading"
                    as="h2"
                    size="display"
                    style={{ color: 'var(--ds-color-text-inverted-default)' }}
                  >
                    Discover the Power of{' '}
                    <span style={{ color: 'var(--ds-color-accent-9)' }}>Beginner's Mind</span>
                  </Heading>
                  <Text style={{ color: 'var(--ds-color-text-inverted-default)' }}>
                    Beginner's mind means approaching life with openness and curiosity,
                    free from fixed ideas. Embrace learning with fresh eyes—explore how our
                    courses nurture this mindset and unlock new possibilities for your growth.
                  </Text>
                </Stack>
                <Button variant="default">See collection</Button>
              </Stack>
            </Box>

            {/* ── Right: related reading cards ── */}
            <Box padding="xxl" style={{ flex: '1 0 0', minWidth: '20rem' }}>
              <Stack gap="md">
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[0]}
                  thumbnailAlt="Zen Mind, Beginner's Mind book cover"
                  title="Zen Mind, Beginner's Mind"
                  duration="Shunryu Suzuki · 4 hours, 30min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[1]}
                  thumbnailAlt="Wherever You Go, There You Are book cover"
                  title="Wherever You Go, There You Are"
                  duration="Jon Kabat-Zinn · 2 hours, 15min"
                  variant="inverted"
                />
                <CardHorizontal
                  thumbnailSrc={BOOK_IMGS[2]}
                  thumbnailAlt="The Miracle of Mindfulness book cover"
                  title="The Miracle of Mindfulness"
                  duration="Thich Nhat Hanh · 1 hour, 10min"
                  variant="inverted"
                />
              </Stack>
            </Box>

          </Inline>
        </Box>
      </Box>

      {/* ── Footer ── reused verbatim from CourseOverview.tsx */}
      <Box
        as="footer"
        style={{
          background: 'var(--ds-color-background-container-inverted)',
          borderTop: '1px solid var(--ds-color-border-inverted)',
        }}
      >
        <Box className="container" paddingY="md">
          <Inline justify="space-between" align="center">
            <img src={`${BASE}logo-dark.svg`} alt="UpSkill" height={32} width={84} />
            <Text size="body-small" style={{ color: 'var(--ds-color-text-inverted-subtle)' }}>
              Terms and Conditions
            </Text>
          </Inline>
        </Box>
      </Box>

    </Box>
  )
}
